name: Bazel BEP Annotate
description: Creates Buildkite annotations from Bazel Event Protocol output
author: https://github.com/buildkite-plugins
requirements:
  - bash
  - jq
  - bc
configuration:
  properties:
    bep_file:
      type: string
    skip_if_no_bep:
      type: boolean
  additionalProperties: false
