steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.1.1:
          folders:
            - tests

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: bazel-annotate

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
            
  - label: ":merge: Test annotation append - Job 1"
    command: |
      # Create a sample BEP file for testing
      echo '{"id":{"buildStarted":{}}, "buildStarted":{"startTimeMillis":1234567890000}}' > bazel-test1.json
      echo '{"id":{"buildFinished":{}}, "buildFinished":{"finishTimeMillis":1234567890100}}' >> bazel-test1.json
      echo '{"id":{"targetCompleted":{"label":"//test1:target1"}}, "completed":{"success":true}}' >> bazel-test1.json
    plugins:
      - ${BUILDKITE_REPO_OWNER:-mcncl}/bazel-annotate${BUILDKITE_COMMIT:+@$BUILDKITE_COMMIT}:
          bep_file: bazel-test1.json
          
  - label: ":merge: Test annotation append - Job 2"
    command: |
      # Create a sample BEP file for testing
      echo '{"id":{"buildStarted":{}}, "buildStarted":{"startTimeMillis":1234567890200}}' > bazel-test2.json
      echo '{"id":{"buildFinished":{}}, "buildFinished":{"finishTimeMillis":1234567890300}}' >> bazel-test2.json
      echo '{"id":{"targetCompleted":{"label":"//test2:target2"}}, "completed":{"success":true}}' >> bazel-test2.json
    plugins:
      - ${BUILDKITE_REPO_OWNER:-mcncl}/bazel-annotate${BUILDKITE_COMMIT:+@$BUILDKITE_COMMIT}:
          bep_file: bazel-test2.json
          
  - label: ":merge: Test annotation append - Job 3"
    command: |
      # Create a sample BEP file for testing
      echo '{"id":{"buildStarted":{}}, "buildStarted":{"startTimeMillis":1234567890400}}' > bazel-test3.json
      echo '{"id":{"buildFinished":{}}, "buildFinished":{"finishTimeMillis":1234567890500}}' >> bazel-test3.json
      echo '{"id":{"targetCompleted":{"label":"//test3:target3"}}, "completed":{"success":true}}' >> bazel-test3.json
    plugins:
      - ${BUILDKITE_REPO_OWNER:-mcncl}/bazel-annotate${BUILDKITE_COMMIT:+@$BUILDKITE_COMMIT}:
          bep_file: bazel-test3.json
